import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../data/sample_feed_comments.dart';
import '../models/models.dart';

Drop mockDrop({
  required String id,
  required String title,
  required String subtitle,
  required double price,
  required String imageUrl,
  required String badge,
  String description = '',
  List<String>? galleryUrls,
  String sellerHandle = 'alex_drops',
}) {
  final seed = 'market_$id';
  final gallery = galleryUrls ??
      <String>[
        imageUrl,
        'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=900&q=80',
      ];
  return Drop(
    id: id,
    title: title,
    subtitle: subtitle,
    price: price,
    imageUrl: imageUrl,
    badge: badge,
    description: description,
    galleryUrls: gallery,
    sellerHandle: sellerHandle,
    likes: mockEngagementCount('${seed}_likes', 620, 9100),
    comments: mockEngagementCount('${seed}_comments', 22, 198),
    feedComments: sampleFeedComments(seed, count: 8),
  );
}

final authProvider = StateProvider<bool>((ref) => true); // Mock logged in state
final mutualFollowProvider = StateProvider<bool>((ref) => true); // Mock mutual follow state

final dipsProvider = Provider<List<Dip>>((ref) {
  return [
    Dip(
      id: '1',
      username: 'alex_drops',
      userAvatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
      mediaUrl: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=800&q=80',
      caption: 'alex_drops The craftsmanship on this piece is unparalleled. #luxury #minimalism',
      timeAgo: '2h ago',
      likes: 1200,
      comments: 84,
      displayName: 'Studio Archive',
      location: 'BERLIN, GERMANY',
      feedComments: sampleFeedComments('dip_1'),
      linkedDrop: mockDrop(
        id: 'd1',
        title: 'Luna Chrono',
        subtitle: 'Obsidian Silver Edition',
        price: 399.00,
        imageUrl: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=200&q=80',
        badge: 'LIMITED RELEASE',
        sellerHandle: 'alex_drops',
      ),
    ),
    Dip(
      id: '2',
      username: 'elenav_studio',
      userAvatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=200&q=80',
      mediaUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',
      caption: 'elenav_studio Perfect setup for the weekend. #tech #setup',
      timeAgo: '5h ago',
      likes: 3400,
      comments: 128,
      displayName: 'Elena V Studio',
      location: 'NEW YORK, USA',
      feedComments: sampleFeedComments('dip_2'),
      linkedDrop: mockDrop(
        id: 'd2',
        title: 'Luna Chrono Pro',
        subtitle: 'Obsidian Silver Edition',
        price: 240.00,
        imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=200&q=80',
        badge: 'NEW ARRIVAL',
        sellerHandle: 'elenav_studio',
      ),
    ),
    Dip(
      id: '3',
      username: 'noir_room',
      userAvatarUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=200&q=80',
      mediaUrl: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=800&q=80',
      caption: 'noir_room Obsidian steel hits different under midnight lighting. #drops #curation',
      timeAgo: '1d ago',
      likes: 980,
      comments: 36,
      displayName: 'Noir Room',
      location: 'BERLIN, GERMANY',
      feedComments: sampleFeedComments('dip_3'),
      linkedDrop: mockDrop(
        id: 'd8',
        title: 'Noir Desk Mat',
        subtitle: 'Deep Black Texture',
        price: 59.00,
        imageUrl: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=200&q=80',
        badge: 'IN STOCK',
        sellerHandle: 'noir_room',
      ),
    ),
    Dip(
      id: '4',
      username: 'squad_crafts',
      userAvatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
      mediaUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
      caption: 'squad_crafts Minimal silhouette, premium feel. Built for daily runs and late nights.',
      timeAgo: '2d ago',
      likes: 2100,
      comments: 77,
      displayName: 'Squad Crafts',
      location: 'PORTLAND, USA',
      feedComments: sampleFeedComments('dip_4'),
      linkedDrop: mockDrop(
        id: 'd4',
        title: 'Aero Sneakers',
        subtitle: 'Triple White',
        price: 220.00,
        imageUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=200&q=80',
        badge: 'IN STOCK',
        sellerHandle: 'squad_crafts',
      ),
    ),
    Dip(
      id: '5',
      username: 'mono_gear',
      userAvatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=200&q=80',
      mediaUrl: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80',
      caption: 'mono_gear Desert sand tones with an obsidian edge. #limited #series',
      timeAgo: '3d ago',
      likes: 1560,
      comments: 58,
      displayName: 'Mono Gear',
      location: 'TOKYO, JAPAN',
      feedComments: sampleFeedComments('dip_5'),
      linkedDrop: mockDrop(
        id: 'd3',
        title: 'Nomad Backpack',
        subtitle: 'Desert Sand',
        price: 185.00,
        imageUrl: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=200&q=80',
        badge: 'LIMITED RELEASE',
        sellerHandle: 'mono_gear',
      ),
    ),
    Dip(
      id: '6',
      username: 'obsidian_audio',
      userAvatarUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=200&q=80',
      mediaUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',
      caption: 'obsidian_audio Headphones + neon reflections = squad-ready. #commerce #sound',
      timeAgo: '4d ago',
      likes: 4100,
      comments: 142,
      displayName: 'Obsidian Audio',
      location: 'LONDON, UK',
      feedComments: sampleFeedComments('dip_6'),
      linkedDrop: mockDrop(
        id: 'd5',
        title: 'Pulse Headphones',
        subtitle: 'Pearl Black Edition',
        price: 129.00,
        imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=200&q=80',
        badge: 'HOT DROP',
        sellerHandle: 'obsidian_audio',
      ),
    ),
    Dip(
      id: '7',
      username: 'atelier_tech',
      userAvatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
      mediaUrl: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=800&q=80',
      caption: 'atelier_tech Precision in every detail. The kind of gear you keep forever.',
      timeAgo: '5d ago',
      likes: 760,
      comments: 24,
      displayName: 'Atelier Tech',
      location: 'PARIS, FRANCE',
      feedComments: sampleFeedComments('dip_7'),
      linkedDrop: mockDrop(
        id: 'd6',
        title: 'Obsidian Dock',
        subtitle: 'Matte Slate Stand',
        price: 89.00,
        imageUrl: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=200&q=80',
        badge: 'IN STOCK',
        sellerHandle: 'atelier_tech',
      ),
    ),
    Dip(
      id: '8',
      username: 'neon_notions',
      userAvatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=200&q=80',
      mediaUrl: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=800&q=80',
      caption: 'neon_notions Clean lines, loud presence. Blue accents always win.',
      timeAgo: '6d ago',
      likes: 2880,
      comments: 101,
      displayName: 'Neon Notions',
      location: 'MIAMI, USA',
      feedComments: sampleFeedComments('dip_8'),
      linkedDrop: mockDrop(
        id: 'd7',
        title: 'Diamond Cable Set',
        subtitle: 'Neon Cyan Coating',
        price: 49.00,
        imageUrl: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=200&q=80',
        badge: 'NEW ARRIVAL',
        sellerHandle: 'neon_notions',
      ),
    ),
    // Sample dips for Explore + Activity suggested / follow-request profiles.
    Dip(
      id: '9',
      username: 'alexvogue',
      userAvatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
      mediaUrl: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=800&q=80',
      caption: 'alexvogue Milan walk — tailoring with a street edge. #squad',
      timeAgo: '3h ago',
      likes: 4200,
      comments: 112,
      displayName: 'Alex Vogue',
      location: 'MILAN, ITALY',
      feedComments: sampleFeedComments('dip_alexvogue_1'),
      linkedDrop: mockDrop(
        id: 'd17',
        title: 'Vogue Linen Blazer',
        subtitle: 'Midnight Navy',
        price: 289.00,
        imageUrl: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=400&q=80',
        badge: 'LIMITED RELEASE',
        sellerHandle: 'alexvogue',
      ),
    ),
    Dip(
      id: '10',
      username: 'alexvogue',
      userAvatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
      mediaUrl: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=800&q=80',
      caption: 'alexvogue Pop-up floor set — obsidian rails and soft light.',
      timeAgo: '1d ago',
      likes: 3100,
      comments: 88,
      displayName: 'Alex Vogue',
      location: 'NEW YORK, USA',
      feedComments: sampleFeedComments('dip_alexvogue_2'),
    ),
    Dip(
      id: '11',
      username: 'studio_noir',
      userAvatarUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=200&q=80',
      mediaUrl: 'https://images.unsplash.com/photo-1558171813-4c088753af8f?auto=format&fit=crop&w=800&q=80',
      caption: 'studio_noir After-hours studio session — blacks on blacks.',
      timeAgo: '5h ago',
      likes: 2800,
      comments: 64,
      displayName: 'Studio Noir',
      location: 'BERLIN, GERMANY',
      feedComments: sampleFeedComments('dip_studio_noir_1'),
      linkedDrop: mockDrop(
        id: 'd19',
        title: 'Noir Wool Coat',
        subtitle: 'Charcoal Longline',
        price: 420.00,
        imageUrl: 'https://images.unsplash.com/photo-1558171813-4c088753af8f?auto=format&fit=crop&w=400&q=80',
        badge: 'IN STOCK',
        sellerHandle: 'studio_noir',
      ),
    ),
    Dip(
      id: '12',
      username: 'studio_noir',
      userAvatarUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=200&q=80',
      mediaUrl: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=800&q=80',
      caption: 'studio_noir Minimal rack edit for the squad capsule.',
      timeAgo: '2d ago',
      likes: 1900,
      comments: 41,
      displayName: 'Studio Noir',
      location: 'BERLIN, GERMANY',
      feedComments: sampleFeedComments('dip_studio_noir_2'),
    ),
    Dip(
      id: '13',
      username: 'mono_gear',
      userAvatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=200&q=80',
      mediaUrl: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80',
      caption: 'mono_gear Desert sand carry — still the daily rotation.',
      timeAgo: '4h ago',
      likes: 5100,
      comments: 156,
      displayName: 'Mono Gear',
      location: 'TOKYO, JAPAN',
      feedComments: sampleFeedComments('dip_mono_gear_ring_1'),
      linkedDrop: mockDrop(
        id: 'd21',
        title: 'Mono Field Pack',
        subtitle: 'Sandstone Canvas',
        price: 165.00,
        imageUrl: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=400&q=80',
        badge: 'NEW ARRIVAL',
        sellerHandle: 'mono_gear',
      ),
    ),
    Dip(
      id: '14',
      username: 'mono_gear',
      userAvatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=200&q=80',
      mediaUrl: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=800&q=80',
      caption: 'mono_gear Keycaps in dark alloy — tactile squad upgrade.',
      timeAgo: '18h ago',
      likes: 3600,
      comments: 92,
      displayName: 'Mono Gear',
      location: 'TOKYO, JAPAN',
      feedComments: sampleFeedComments('dip_mono_gear_ring_2'),
    ),
    Dip(
      id: '15',
      username: 'elenav',
      userAvatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&q=80',
      mediaUrl: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=800&q=80',
      caption: 'elenav Silver chrono on marble — everyday luxury.',
      timeAgo: '6h ago',
      likes: 8900,
      comments: 240,
      displayName: 'Elena Vasquez',
      location: 'LOS ANGELES, USA',
      feedComments: sampleFeedComments('dip_elenav_1'),
      linkedDrop: mockDrop(
        id: 'd23',
        title: 'Vasquez Steel Band',
        subtitle: 'Brushed Silver',
        price: 199.00,
        imageUrl: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=400&q=80',
        badge: 'HOT DROP',
        sellerHandle: 'elenav',
      ),
    ),
    Dip(
      id: '16',
      username: 'elenav',
      userAvatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&q=80',
      mediaUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',
      caption: 'elenav Headphones + gold hour — studio vibes only.',
      timeAgo: '1d ago',
      likes: 6200,
      comments: 178,
      displayName: 'Elena Vasquez',
      location: 'LOS ANGELES, USA',
      feedComments: sampleFeedComments('dip_elenav_2'),
    ),
    Dip(
      id: '17',
      username: 'dip_archive',
      userAvatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=200&q=80',
      mediaUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
      caption: 'dip_archive Archiving the triple-white Aero — grail status.',
      timeAgo: '8h ago',
      likes: 2400,
      comments: 71,
      displayName: 'Dip Archive',
      location: 'CHICAGO, USA',
      feedComments: sampleFeedComments('dip_dip_archive_1'),
      linkedDrop: mockDrop(
        id: 'd25',
        title: 'Archive Aero Vault',
        subtitle: 'Triple White Reserve',
        price: 260.00,
        imageUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=400&q=80',
        badge: 'LIMITED RELEASE',
        sellerHandle: 'dip_archive',
      ),
    ),
    Dip(
      id: '18',
      username: 'dip_archive',
      userAvatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=200&q=80',
      mediaUrl: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=800&q=80',
      caption: 'dip_archive Bottle study — pearl cap under soft box.',
      timeAgo: '3d ago',
      likes: 1800,
      comments: 54,
      displayName: 'Dip Archive',
      location: 'CHICAGO, USA',
      feedComments: sampleFeedComments('dip_dip_archive_2'),
    ),
    Dip(
      id: '19',
      username: 'kaze_atelier',
      userAvatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
      mediaUrl: 'https://images.unsplash.com/photo-1469334031218-e382a71b716b?auto=format&fit=crop&w=800&q=80',
      caption: 'kaze_atelier Layered linen in motion — Kyoto breeze.',
      timeAgo: '12h ago',
      likes: 3300,
      comments: 96,
      displayName: 'Kaze Atelier',
      location: 'KYOTO, JAPAN',
      feedComments: sampleFeedComments('dip_kaze_1'),
      linkedDrop: mockDrop(
        id: 'd27',
        title: 'Kaze Layered Kimono',
        subtitle: 'Fog Grey Silk',
        price: 340.00,
        imageUrl: 'https://images.unsplash.com/photo-1469334031218-e382a71b716b?auto=format&fit=crop&w=400&q=80',
        badge: 'NEW ARRIVAL',
        sellerHandle: 'kaze_atelier',
      ),
    ),
    Dip(
      id: '20',
      username: 'kaze_atelier',
      userAvatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
      mediaUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=800&q=80',
      caption: 'kaze_atelier Flagship window — light as material.',
      timeAgo: '2d ago',
      likes: 2100,
      comments: 58,
      displayName: 'Kaze Atelier',
      location: 'KYOTO, JAPAN',
      feedComments: sampleFeedComments('dip_kaze_2'),
    ),
    Dip(
      id: '21',
      username: 'noir_supply',
      userAvatarUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=200&q=80',
      mediaUrl: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80',
      caption: 'noir_supply Desk mat depth — texture for late sessions.',
      timeAgo: '7h ago',
      likes: 4100,
      comments: 120,
      displayName: 'Noir Supply Co.',
      location: 'SAN FRANCISCO, USA',
      feedComments: sampleFeedComments('dip_noir_supply_1'),
      linkedDrop: mockDrop(
        id: 'd29',
        title: 'Supply Desk Mat XL',
        subtitle: 'Obsidian Loop',
        price: 72.00,
        imageUrl: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=400&q=80',
        badge: 'IN STOCK',
        sellerHandle: 'noir_supply',
      ),
    ),
    Dip(
      id: '22',
      username: 'noir_supply',
      userAvatarUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=200&q=80',
      mediaUrl: 'https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?auto=format&fit=crop&w=800&q=80',
      caption: 'noir_supply Slim wallet weave — carbon black.',
      timeAgo: '1d ago',
      likes: 2900,
      comments: 77,
      displayName: 'Noir Supply Co.',
      location: 'SAN FRANCISCO, USA',
      feedComments: sampleFeedComments('dip_noir_supply_2'),
    ),
    Dip(
      id: '23',
      username: 'pixel_muse',
      userAvatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=200&q=80',
      mediaUrl: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=800&q=80',
      caption: 'pixel_muse Neon sticker drop — cyan edge pack.',
      timeAgo: '4h ago',
      likes: 6700,
      comments: 201,
      displayName: 'Muse Park',
      location: 'SEOUL, KOREA',
      feedComments: sampleFeedComments('dip_pixel_muse_1'),
      linkedDrop: mockDrop(
        id: 'd31',
        title: 'Pixel Sticker Vault',
        subtitle: 'Cyan Edge Pack',
        price: 24.00,
        imageUrl: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=400&q=80',
        badge: 'NEW ARRIVAL',
        sellerHandle: 'pixel_muse',
      ),
    ),
    Dip(
      id: '24',
      username: 'pixel_muse',
      userAvatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=200&q=80',
      mediaUrl: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=800&q=80',
      caption: 'pixel_muse Dock render study — matte slate stand.',
      timeAgo: '2d ago',
      likes: 4400,
      comments: 133,
      displayName: 'Muse Park',
      location: 'SEOUL, KOREA',
      feedComments: sampleFeedComments('dip_pixel_muse_2'),
    ),
  ];
});

final dropsProvider = Provider<List<Drop>>((ref) {
  return [
    mockDrop(
      id: 'd1',
      title: 'Studio Pro H1',
      subtitle: 'Matte Carbon',
      price: 399.00,
      imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=400&q=80',
      badge: 'IN STOCK',
      description: 'Designed for the modern explorer. Featuring a minimalist brushed steel finish...',
      sellerHandle: 'alex_drops',
    ),
    mockDrop(
      id: 'd2',
      title: 'Luna Chrono Pro',
      subtitle: 'Obsidian Silver Edition',
      price: 240.00,
      imageUrl: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=400&q=80',
      badge: 'NEW ARRIVAL',
      description: 'Designed for the modern explorer. Featuring a minimalist brushed steel finish...',
      sellerHandle: 'elenav_studio',
    ),
    mockDrop(
      id: 'd3',
      title: 'Nomad Backpack',
      subtitle: 'Desert Sand',
      price: 185.00,
      imageUrl: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=400&q=80',
      badge: 'LIMITED RELEASE',
      description: 'Durable, water-resistant, and stylish.',
      sellerHandle: 'mono_gear',
    ),
    mockDrop(
      id: 'd4',
      title: 'Aero Sneakers',
      subtitle: 'Triple White',
      price: 220.00,
      imageUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=400&q=80',
      badge: 'IN STOCK',
      description: 'Lightweight and breathable for everyday wear.',
      sellerHandle: 'squad_crafts',
    ),
    mockDrop(
      id: 'd5',
      title: 'Pulse Headphones',
      subtitle: 'Pearl Black Edition',
      price: 129.00,
      imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=400&q=80',
      badge: 'HOT DROP',
      description: 'Moody bass, clean mids, and a matte finish you can feel.',
      sellerHandle: 'obsidian_audio',
    ),
    mockDrop(
      id: 'd6',
      title: 'Obsidian Dock',
      subtitle: 'Matte Slate Stand',
      price: 89.00,
      imageUrl: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=400&q=80',
      badge: 'IN STOCK',
      description: 'A minimalist charging dock with an Obsidian-grade build.',
      sellerHandle: 'atelier_tech',
    ),
    mockDrop(
      id: 'd7',
      title: 'Diamond Cable Set',
      subtitle: 'Neon Cyan Coating',
      price: 49.00,
      imageUrl: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=400&q=80',
      badge: 'NEW ARRIVAL',
      description: 'Braided strength with a neon accent that pops under light.',
      sellerHandle: 'neon_notions',
    ),
    mockDrop(
      id: 'd8',
      title: 'Noir Desk Mat',
      subtitle: 'Deep Black Texture',
      price: 59.00,
      imageUrl: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=400&q=80',
      badge: 'IN STOCK',
      description: 'Soft under your wrists, premium for every day work sessions.',
      sellerHandle: 'noir_room',
    ),
    mockDrop(
      id: 'd9',
      title: 'Obsidian Bottle',
      subtitle: 'Pearl Silver Cap',
      price: 39.00,
      imageUrl: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=400&q=80',
      badge: 'NEW ARRIVAL',
      description: 'Keep it cold. Keep it clean. Built to look good everywhere.',
      sellerHandle: 'alex_drops',
    ),
    mockDrop(
      id: 'd10',
      title: 'Studio Lamp V2',
      subtitle: 'Neon Cyan Halo',
      price: 149.00,
      imageUrl: 'https://images.unsplash.com/photo-1519710164239-da123dc03ef4?auto=format&fit=crop&w=400&q=80',
      badge: 'LIMITED RELEASE',
      description: 'A soft glow with deep blacks and a neon edge.',
      sellerHandle: 'elenav_studio',
    ),
    mockDrop(
      id: 'd11',
      title: 'Travel Case',
      subtitle: 'Obsidian Shell',
      price: 75.00,
      imageUrl: 'https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?auto=format&fit=crop&w=400&q=80',
      badge: 'IN STOCK',
      description: 'Slim, sturdy, and ready for carry-on adventures.',
      sellerHandle: 'noir_room',
    ),
    mockDrop(
      id: 'd12',
      title: 'Matte Keycaps',
      subtitle: 'Dark Alloy Set',
      price: 55.00,
      imageUrl: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=400&q=80',
      badge: 'HOT DROP',
      description: 'Tactile feel with a matte texture that stays premium.',
      sellerHandle: 'mono_gear',
    ),
    mockDrop(
      id: 'd13',
      title: 'Neon Accent Sticker Pack',
      subtitle: 'Cyan + Purple Edition',
      price: 12.00,
      imageUrl: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=400&q=80',
      badge: 'NEW ARRIVAL',
      description: 'Quick personality upgrade for laptops, cases, and gear.',
      sellerHandle: 'neon_notions',
    ),
    mockDrop(
      id: 'd14',
      title: 'Obsidian Wallet',
      subtitle: 'Slim Carbon Weave',
      price: 45.00,
      imageUrl: 'https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?auto=format&fit=crop&w=400&q=80',
      badge: 'IN STOCK',
      description: 'Minimal carry with a premium weave and clean edges.',
      sellerHandle: 'squad_crafts',
    ),
    mockDrop(
      id: 'd15',
      title: 'Ultra Matte Phone Grip',
      subtitle: 'Blue Neon Pin',
      price: 19.00,
      imageUrl: 'https://images.unsplash.com/photo-1519710164239-da123dc03ef4?auto=format&fit=crop&w=400&q=80',
      badge: 'LIMITED RELEASE',
      description: 'A secure grip with a neon accent for day-to-night style.',
      sellerHandle: 'obsidian_audio',
    ),
    mockDrop(
      id: 'd16',
      title: 'Squad Hoodie',
      subtitle: 'Obsidian Black Knit',
      price: 99.00,
      imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=400&q=80',
      badge: 'IN STOCK',
      description: 'Soft, structured, and built for late-night dip sessions.',
      sellerHandle: 'atelier_tech',
    ),
    mockDrop(
      id: 'd17',
      title: 'Vogue Linen Blazer',
      subtitle: 'Midnight Navy',
      price: 289.00,
      imageUrl: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=400&q=80',
      badge: 'LIMITED RELEASE',
      description: 'Structured linen with a midnight drape — editorial squad uniform.',
      sellerHandle: 'alexvogue',
    ),
    mockDrop(
      id: 'd18',
      title: 'Chen Silk Scarf',
      subtitle: 'Ivory Stripe',
      price: 98.00,
      imageUrl: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=400&q=80',
      badge: 'NEW ARRIVAL',
      description: 'Lightweight silk with a subtle stripe for layering.',
      sellerHandle: 'alexvogue',
    ),
    mockDrop(
      id: 'd19',
      title: 'Noir Wool Coat',
      subtitle: 'Charcoal Longline',
      price: 420.00,
      imageUrl: 'https://images.unsplash.com/photo-1558171813-4c088753af8f?auto=format&fit=crop&w=400&q=80',
      badge: 'IN STOCK',
      description: 'Longline wool with a deep charcoal finish for winter nights.',
      sellerHandle: 'studio_noir',
    ),
    mockDrop(
      id: 'd20',
      title: 'Studio Rib Knit',
      subtitle: 'Black Onyx',
      price: 128.00,
      imageUrl: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=400&q=80',
      badge: 'HOT DROP',
      description: 'Ribbed knit with a soft hand and clean edge.',
      sellerHandle: 'studio_noir',
    ),
    mockDrop(
      id: 'd21',
      title: 'Mono Field Pack',
      subtitle: 'Sandstone Canvas',
      price: 165.00,
      imageUrl: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=400&q=80',
      badge: 'NEW ARRIVAL',
      description: 'Field-ready canvas with modular straps.',
      sellerHandle: 'mono_gear',
    ),
    mockDrop(
      id: 'd22',
      title: 'Mono Tech Sling',
      subtitle: 'Graphite Webbing',
      price: 95.00,
      imageUrl: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=400&q=80',
      badge: 'IN STOCK',
      description: 'Compact sling with matte hardware.',
      sellerHandle: 'mono_gear',
    ),
    mockDrop(
      id: 'd23',
      title: 'Vasquez Steel Band',
      subtitle: 'Brushed Silver',
      price: 199.00,
      imageUrl: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=400&q=80',
      badge: 'HOT DROP',
      description: 'Brushed steel band with a slim profile.',
      sellerHandle: 'elenav',
    ),
    mockDrop(
      id: 'd24',
      title: 'Vasquez Pearl Studs',
      subtitle: 'Sterling Pair',
      price: 64.00,
      imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=400&q=80',
      badge: 'NEW ARRIVAL',
      description: 'Pearl studs with a soft glow for day-to-night.',
      sellerHandle: 'elenav',
    ),
    mockDrop(
      id: 'd25',
      title: 'Archive Aero Vault',
      subtitle: 'Triple White Reserve',
      price: 260.00,
      imageUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=400&q=80',
      badge: 'LIMITED RELEASE',
      description: 'Vault-grade triple white with archive certification.',
      sellerHandle: 'dip_archive',
    ),
    mockDrop(
      id: 'd26',
      title: 'Archive Bottle Lab',
      subtitle: 'Pearl Cap Study',
      price: 44.00,
      imageUrl: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=400&q=80',
      badge: 'IN STOCK',
      description: 'Lab edition bottle with pearl cap finish.',
      sellerHandle: 'dip_archive',
    ),
    mockDrop(
      id: 'd27',
      title: 'Kaze Layered Kimono',
      subtitle: 'Fog Grey Silk',
      price: 340.00,
      imageUrl: 'https://images.unsplash.com/photo-1469334031218-e382a71b716b?auto=format&fit=crop&w=400&q=80',
      badge: 'NEW ARRIVAL',
      description: 'Layered silk with fog grey drape — Kyoto craft.',
      sellerHandle: 'kaze_atelier',
    ),
    mockDrop(
      id: 'd28',
      title: 'Kaze Linen Wrap',
      subtitle: 'Stone Wash',
      price: 188.00,
      imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=400&q=80',
      badge: 'LIMITED RELEASE',
      description: 'Stone-washed linen wrap for transitional weather.',
      sellerHandle: 'kaze_atelier',
    ),
    mockDrop(
      id: 'd29',
      title: 'Supply Desk Mat XL',
      subtitle: 'Obsidian Loop',
      price: 72.00,
      imageUrl: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=400&q=80',
      badge: 'IN STOCK',
      description: 'Extra-wide desk mat with obsidian loop texture.',
      sellerHandle: 'noir_supply',
    ),
    mockDrop(
      id: 'd30',
      title: 'Supply Carbon Wallet',
      subtitle: 'Slim Weave',
      price: 52.00,
      imageUrl: 'https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?auto=format&fit=crop&w=400&q=80',
      badge: 'IN STOCK',
      description: 'Slim carbon weave wallet with matte finish.',
      sellerHandle: 'noir_supply',
    ),
    mockDrop(
      id: 'd31',
      title: 'Pixel Sticker Vault',
      subtitle: 'Cyan Edge Pack',
      price: 24.00,
      imageUrl: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=400&q=80',
      badge: 'NEW ARRIVAL',
      description: 'Neon cyan edge stickers for laptops and cases.',
      sellerHandle: 'pixel_muse',
    ),
    mockDrop(
      id: 'd32',
      title: 'Muse Dock Render',
      subtitle: 'Matte Slate Stand',
      price: 79.00,
      imageUrl: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=400&q=80',
      badge: 'HOT DROP',
      description: 'Matte slate dock stand inspired by studio renders.',
      sellerHandle: 'pixel_muse',
    ),
  ];
});

/// Resolved [Drop] for detail routes (comments, likes).
final dropByIdProvider = Provider.family<Drop?, String>((ref, id) {
  final drops = ref.watch(dropsProvider);
  for (final d in drops) {
    if (d.id == id) return d;
  }
  return null;
});

/// Logged-in user (self) — matches tab profile & feed “me”.
final userProfileProvider = Provider<UserProfile>((ref) {
  return UserProfile(
    id: 'me',
    username: '@ALEX_DROPS',
    displayName: 'Alex Obsidian',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80',
    bio:
        'Redefining the digital luxury landscape through minimalist curation and obsidian aesthetics.',
    followers: 12400,
    following: 850,
    dropsCount: 42,
    isFollowing: false,
  );
});

const _meHandle = 'alex_drops';

/// Mock public profiles keyed by feed username (lowercase, no @).
final publicProfilesMapProvider = Provider<Map<String, UserProfile>>((ref) {
  UserProfile p({
    required String handle,
    required String display,
    required String avatar,
    required String bio,
    int followers = 8000,
    int following = 400,
    int drops = 24,
  }) {
    return UserProfile(
      id: handle,
      username: '@${handle.toUpperCase()}',
      displayName: display,
      avatarUrl: avatar,
      bio: bio,
      followers: followers,
      following: following,
      dropsCount: drops,
      isFollowing: false,
    );
  }

  return {
    'elenav_studio': p(
      handle: 'elenav_studio',
      display: 'Elena V Studio',
      avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=300&q=80',
      bio: 'Tech setups, weekend drops, and clean lines. NYC.',
      followers: 28900,
      following: 890,
      drops: 38,
    ),
    'noir_room': p(
      handle: 'noir_room',
      display: 'Noir Room',
      avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=300&q=80',
      bio: 'Midnight curation. Berlin.',
      followers: 15200,
      following: 612,
      drops: 19,
    ),
    'squad_crafts': p(
      handle: 'squad_crafts',
      display: 'Squad Crafts',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80',
      bio: 'Footwear & daily carry. Portland-made energy.',
      followers: 22100,
      following: 540,
      drops: 31,
    ),
    'mono_gear': p(
      handle: 'mono_gear',
      display: 'Mono Gear',
      avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=300&q=80',
      bio: 'Desert tones, obsidian details. Tokyo.',
      followers: 9400,
      following: 320,
      drops: 17,
    ),
    'obsidian_audio': p(
      handle: 'obsidian_audio',
      display: 'Obsidian Audio',
      avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=300&q=80',
      bio: 'Sound you can feel. London.',
      followers: 41200,
      following: 1100,
      drops: 56,
    ),
    'atelier_tech': p(
      handle: 'atelier_tech',
      display: 'Atelier Tech',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80',
      bio: 'Precision gear for people who notice the details. Paris.',
      followers: 6700,
      following: 210,
      drops: 12,
    ),
    'neon_notions': p(
      handle: 'neon_notions',
      display: 'Neon Notions',
      avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=300&q=80',
      bio: 'Blue accents always win. Miami.',
      followers: 19800,
      following: 720,
      drops: 27,
    ),
    // Inbox threads ([inboxThreadsProvider]) — same handles & avatars as messages.
    'alexrivera': p(
      handle: 'alexrivera',
      display: 'Alex Rivera',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80',
      bio: 'Squad buys, Luna drops, and late-night fits. LA.',
      followers: 18400,
      following: 412,
      drops: 28,
    ),
    'sarahc': p(
      handle: 'sarahc',
      display: 'Sarah Chen',
      avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&w=300&q=80',
      bio: 'Tracking, logistics, zero drama. SF.',
      followers: 9200,
      following: 310,
      drops: 14,
    ),
    'marcus_vibe': p(
      handle: 'marcus_vibe',
      display: 'Marcus Thorne',
      avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=300&q=80',
      bio: 'Chrono enthusiast. If it ticks, I’m interested.',
      followers: 11200,
      following: 520,
      drops: 21,
    ),
    'lilavogue': p(
      handle: 'lilavogue',
      display: 'Lila Vogue',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=300&q=80',
      bio: 'Drop alerts & squad energy. NYC.',
      followers: 25600,
      following: 890,
      drops: 34,
    ),
    'jordan_steel': p(
      handle: 'jordan_steel',
      display: 'Jordan Steel',
      avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=300&q=80',
      bio: 'Pickup spots & meetups. Chicago.',
      followers: 7400,
      following: 198,
      drops: 11,
    ),
    // Explore “Discover creators” + Activity follow requests / suggested.
    'alexvogue': p(
      handle: 'alexvogue',
      display: 'Alexander Chen',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80',
      bio: 'Editorial fits, runway energy, squad-first drops. NYC.',
      followers: 22400,
      following: 720,
      drops: 4,
    ),
    'studio_noir': p(
      handle: 'studio_noir',
      display: 'Jordan Blake',
      avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=300&q=80',
      bio: 'Midnight palettes, studio-only releases. Berlin.',
      followers: 18900,
      following: 640,
      drops: 4,
    ),
    'elenav': p(
      handle: 'elenav',
      display: 'Elena Vasquez',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=300&q=80',
      bio: 'Color theory, luxury basics, and honest reviews. LA.',
      followers: 31200,
      following: 910,
      drops: 4,
    ),
    'dip_archive': p(
      handle: 'dip_archive',
      display: 'Marcus Cole',
      avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=300&q=80',
      bio: 'Archiving the best drops — documentation and curation.',
      followers: 9600,
      following: 402,
      drops: 4,
    ),
    'kaze_atelier': p(
      handle: 'kaze_atelier',
      display: 'Kaze Atelier',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
      bio: 'Wind-light textiles and hand-finished layers. Kyoto.',
      followers: 7400,
      following: 310,
      drops: 4,
    ),
    'noir_supply': p(
      handle: 'noir_supply',
      display: 'Noir Supply Co.',
      avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=300&q=80',
      bio: 'All-black essentials for the squad uniform. SF.',
      followers: 15100,
      following: 520,
      drops: 4,
    ),
    'pixel_muse': p(
      handle: 'pixel_muse',
      display: 'Muse Park',
      avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=300&q=80',
      bio: 'Digital art drops, prints, and neon retros. Seoul.',
      followers: 21200,
      following: 880,
      drops: 4,
    ),
  };
});

/// Resolve profile for product seller row or `/profile/u/:handle`.
final profileByHandleProvider = Provider.family<UserProfile?, String>((ref, raw) {
  final h = raw.trim().toLowerCase().replaceAll('@', '');
  if (h.isEmpty || h == _meHandle) return ref.watch(userProfileProvider);
  return ref.watch(publicProfilesMapProvider)[h];
});
