import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../data/sample_feed_comments.dart';
import '../models/models.dart';

Drop mockDrop({
  required String id,
  required String title,
  required String subtitle,
  required double price,
  required String imageUrl,
  required String badge,
  String description = '',
  List<String>? galleryUrls,
  String sellerHandle = 'alex_drops',
}) {
  final seed = 'market_$id';
  final gallery = galleryUrls ??
      <String>[
        imageUrl,
        'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=900&q=80',
      ];
  return Drop(
    id: id,
    title: title,
    subtitle: subtitle,
    price: price,
    imageUrl: imageUrl,
    badge: badge,
    description: description,
    galleryUrls: gallery,
    sellerHandle: sellerHandle,
    likes: mockEngagementCount('${seed}_likes', 620, 9100),
    comments: mockEngagementCount('${seed}_comments', 22, 198),
    feedComments: sampleFeedComments(seed, count: 8),
  );
}

final authProvider = StateProvider<bool>((ref) => true); // Mock logged in state
final mutualFollowProvider = StateProvider<bool>((ref) => true); // Mock mutual follow state

final dipsProvider = Provider<List<Dip>>((ref) {
  return [
    Dip(
      id: '1',
      username: 'alex_drops',
      userAvatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
      mediaUrl: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=800&q=80',
      caption: 'alex_drops The craftsmanship on this piece is unparalleled. #luxury #minimalism',
      timeAgo: '2h ago',
      likes: 1200,
      comments: 84,
      displayName: 'Studio Archive',
      location: 'BERLIN, GERMANY',
      feedComments: sampleFeedComments('dip_1'),
      linkedDrop: mockDrop(
        id: 'd1',
        title: 'Luna Chrono',
        subtitle: 'Obsidian Silver Edition',
        price: 399.00,
        imageUrl: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=200&q=80',
        badge: 'LIMITED RELEASE',
        sellerHandle: 'alex_drops',
      ),
    ),
    Dip(
      id: '2',
      username: 'elenav_studio',
      userAvatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=200&q=80',
      mediaUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',
      caption: 'elenav_studio Perfect setup for the weekend. #tech #setup',
      timeAgo: '5h ago',
      likes: 3400,
      comments: 128,
      displayName: 'Elena V Studio',
      location: 'NEW YORK, USA',
      feedComments: sampleFeedComments('dip_2'),
      linkedDrop: mockDrop(
        id: 'd2',
        title: 'Luna Chrono Pro',
        subtitle: 'Obsidian Silver Edition',
        price: 240.00,
        imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=200&q=80',
        badge: 'NEW ARRIVAL',
        sellerHandle: 'elenav_studio',
      ),
    ),
    Dip(
      id: '3',
      username: 'noir_room',
      userAvatarUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=200&q=80',
      mediaUrl: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=800&q=80',
      caption: 'noir_room Obsidian steel hits different under midnight lighting. #drops #curation',
      timeAgo: '1d ago',
      likes: 980,
      comments: 36,
      displayName: 'Noir Room',
      location: 'BERLIN, GERMANY',
      feedComments: sampleFeedComments('dip_3'),
      linkedDrop: mockDrop(
        id: 'd8',
        title: 'Noir Desk Mat',
        subtitle: 'Deep Black Texture',
        price: 59.00,
        imageUrl: 'https://images.unsplash.com/photo-1522199798949-7b3c2a49c0b5?auto=format&fit=crop&w=200&q=80',
        badge: 'IN STOCK',
        sellerHandle: 'noir_room',
      ),
    ),
    Dip(
      id: '4',
      username: 'squad_crafts',
      userAvatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
      mediaUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
      caption: 'squad_crafts Minimal silhouette, premium feel. Built for daily runs and late nights.',
      timeAgo: '2d ago',
      likes: 2100,
      comments: 77,
      displayName: 'Squad Crafts',
      location: 'PORTLAND, USA',
      feedComments: sampleFeedComments('dip_4'),
      linkedDrop: mockDrop(
        id: 'd4',
        title: 'Aero Sneakers',
        subtitle: 'Triple White',
        price: 220.00,
        imageUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=200&q=80',
        badge: 'IN STOCK',
        sellerHandle: 'squad_crafts',
      ),
    ),
    Dip(
      id: '5',
      username: 'mono_gear',
      userAvatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=200&q=80',
      mediaUrl: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80',
      caption: 'mono_gear Desert sand tones with an obsidian edge. #limited #series',
      timeAgo: '3d ago',
      likes: 1560,
      comments: 58,
      displayName: 'Mono Gear',
      location: 'TOKYO, JAPAN',
      feedComments: sampleFeedComments('dip_5'),
      linkedDrop: mockDrop(
        id: 'd3',
        title: 'Nomad Backpack',
        subtitle: 'Desert Sand',
        price: 185.00,
        imageUrl: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=200&q=80',
        badge: 'LIMITED RELEASE',
        sellerHandle: 'mono_gear',
      ),
    ),
    Dip(
      id: '6',
      username: 'obsidian_audio',
      userAvatarUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=200&q=80',
      mediaUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',
      caption: 'obsidian_audio Headphones + neon reflections = squad-ready. #commerce #sound',
      timeAgo: '4d ago',
      likes: 4100,
      comments: 142,
      displayName: 'Obsidian Audio',
      location: 'LONDON, UK',
      feedComments: sampleFeedComments('dip_6'),
      linkedDrop: mockDrop(
        id: 'd5',
        title: 'Pulse Headphones',
        subtitle: 'Pearl Black Edition',
        price: 129.00,
        imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=200&q=80',
        badge: 'HOT DROP',
        sellerHandle: 'obsidian_audio',
      ),
    ),
    Dip(
      id: '7',
      username: 'atelier_tech',
      userAvatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
      mediaUrl: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=800&q=80',
      caption: 'atelier_tech Precision in every detail. The kind of gear you keep forever.',
      timeAgo: '5d ago',
      likes: 760,
      comments: 24,
      displayName: 'Atelier Tech',
      location: 'PARIS, FRANCE',
      feedComments: sampleFeedComments('dip_7'),
      linkedDrop: mockDrop(
        id: 'd6',
        title: 'Obsidian Dock',
        subtitle: 'Matte Slate Stand',
        price: 89.00,
        imageUrl: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=200&q=80',
        badge: 'IN STOCK',
        sellerHandle: 'atelier_tech',
      ),
    ),
    Dip(
      id: '8',
      username: 'neon_notions',
      userAvatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=200&q=80',
      mediaUrl: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=800&q=80',
      caption: 'neon_notions Clean lines, loud presence. Blue accents always win.',
      timeAgo: '6d ago',
      likes: 2880,
      comments: 101,
      displayName: 'Neon Notions',
      location: 'MIAMI, USA',
      feedComments: sampleFeedComments('dip_8'),
      linkedDrop: mockDrop(
        id: 'd7',
        title: 'Diamond Cable Set',
        subtitle: 'Neon Cyan Coating',
        price: 49.00,
        imageUrl: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=200&q=80',
        badge: 'NEW ARRIVAL',
        sellerHandle: 'neon_notions',
      ),
    ),
  ];
});

final dropsProvider = Provider<List<Drop>>((ref) {
  return [
    mockDrop(
      id: 'd1',
      title: 'Studio Pro H1',
      subtitle: 'Matte Carbon',
      price: 399.00,
      imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=400&q=80',
      badge: 'IN STOCK',
      description: 'Designed for the modern explorer. Featuring a minimalist brushed steel finish...',
      sellerHandle: 'alex_drops',
    ),
    mockDrop(
      id: 'd2',
      title: 'Luna Chrono Pro',
      subtitle: 'Obsidian Silver Edition',
      price: 240.00,
      imageUrl: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=400&q=80',
      badge: 'NEW ARRIVAL',
      description: 'Designed for the modern explorer. Featuring a minimalist brushed steel finish...',
      sellerHandle: 'elenav_studio',
    ),
    mockDrop(
      id: 'd3',
      title: 'Nomad Backpack',
      subtitle: 'Desert Sand',
      price: 185.00,
      imageUrl: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=400&q=80',
      badge: 'LIMITED RELEASE',
      description: 'Durable, water-resistant, and stylish.',
      sellerHandle: 'mono_gear',
    ),
    mockDrop(
      id: 'd4',
      title: 'Aero Sneakers',
      subtitle: 'Triple White',
      price: 220.00,
      imageUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=400&q=80',
      badge: 'IN STOCK',
      description: 'Lightweight and breathable for everyday wear.',
      sellerHandle: 'squad_crafts',
    ),
    mockDrop(
      id: 'd5',
      title: 'Pulse Headphones',
      subtitle: 'Pearl Black Edition',
      price: 129.00,
      imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=400&q=80',
      badge: 'HOT DROP',
      description: 'Moody bass, clean mids, and a matte finish you can feel.',
      sellerHandle: 'obsidian_audio',
    ),
    mockDrop(
      id: 'd6',
      title: 'Obsidian Dock',
      subtitle: 'Matte Slate Stand',
      price: 89.00,
      imageUrl: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=400&q=80',
      badge: 'IN STOCK',
      description: 'A minimalist charging dock with an Obsidian-grade build.',
      sellerHandle: 'atelier_tech',
    ),
    mockDrop(
      id: 'd7',
      title: 'Diamond Cable Set',
      subtitle: 'Neon Cyan Coating',
      price: 49.00,
      imageUrl: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=400&q=80',
      badge: 'NEW ARRIVAL',
      description: 'Braided strength with a neon accent that pops under light.',
      sellerHandle: 'neon_notions',
    ),
    mockDrop(
      id: 'd8',
      title: 'Noir Desk Mat',
      subtitle: 'Deep Black Texture',
      price: 59.00,
      imageUrl: 'https://images.unsplash.com/photo-1522199798949-7b3c2a49c0b5?auto=format&fit=crop&w=400&q=80',
      badge: 'IN STOCK',
      description: 'Soft under your wrists, premium for every day work sessions.',
      sellerHandle: 'noir_room',
    ),
    mockDrop(
      id: 'd9',
      title: 'Obsidian Bottle',
      subtitle: 'Pearl Silver Cap',
      price: 39.00,
      imageUrl: 'https://images.unsplash.com/photo-1512410265697-3b3c2e1c1b2f?auto=format&fit=crop&w=400&q=80',
      badge: 'NEW ARRIVAL',
      description: 'Keep it cold. Keep it clean. Built to look good everywhere.',
      sellerHandle: 'alex_drops',
    ),
    mockDrop(
      id: 'd10',
      title: 'Studio Lamp V2',
      subtitle: 'Neon Cyan Halo',
      price: 149.00,
      imageUrl: 'https://images.unsplash.com/photo-1519710164239-da123dc03ef4?auto=format&fit=crop&w=400&q=80',
      badge: 'LIMITED RELEASE',
      description: 'A soft glow with deep blacks and a neon edge.',
      sellerHandle: 'elenav_studio',
    ),
    mockDrop(
      id: 'd11',
      title: 'Travel Case',
      subtitle: 'Obsidian Shell',
      price: 75.00,
      imageUrl: 'https://images.unsplash.com/photo-1526481280695-3c687fd5432c?auto=format&fit=crop&w=400&q=80',
      badge: 'IN STOCK',
      description: 'Slim, sturdy, and ready for carry-on adventures.',
      sellerHandle: 'noir_room',
    ),
    mockDrop(
      id: 'd12',
      title: 'Matte Keycaps',
      subtitle: 'Dark Alloy Set',
      price: 55.00,
      imageUrl: 'https://images.unsplash.com/photo-1541147395347-56b2bfa9c1a8?auto=format&fit=crop&w=400&q=80',
      badge: 'HOT DROP',
      description: 'Tactile feel with a matte texture that stays premium.',
      sellerHandle: 'mono_gear',
    ),
    mockDrop(
      id: 'd13',
      title: 'Neon Accent Sticker Pack',
      subtitle: 'Cyan + Purple Edition',
      price: 12.00,
      imageUrl: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=400&q=80',
      badge: 'NEW ARRIVAL',
      description: 'Quick personality upgrade for laptops, cases, and gear.',
      sellerHandle: 'neon_notions',
    ),
    mockDrop(
      id: 'd14',
      title: 'Obsidian Wallet',
      subtitle: 'Slim Carbon Weave',
      price: 45.00,
      imageUrl: 'https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?auto=format&fit=crop&w=400&q=80',
      badge: 'IN STOCK',
      description: 'Minimal carry with a premium weave and clean edges.',
      sellerHandle: 'squad_crafts',
    ),
    mockDrop(
      id: 'd15',
      title: 'Ultra Matte Phone Grip',
      subtitle: 'Blue Neon Pin',
      price: 19.00,
      imageUrl: 'https://images.unsplash.com/photo-1510557880182-3fefb5b5d39a?auto=format&fit=crop&w=400&q=80',
      badge: 'LIMITED RELEASE',
      description: 'A secure grip with a neon accent for day-to-night style.',
      sellerHandle: 'obsidian_audio',
    ),
    mockDrop(
      id: 'd16',
      title: 'Squad Hoodie',
      subtitle: 'Obsidian Black Knit',
      price: 99.00,
      imageUrl: 'https://images.unsplash.com/photo-1520975958225-9b8a6a0e7b2f?auto=format&fit=crop&w=400&q=80',
      badge: 'IN STOCK',
      description: 'Soft, structured, and built for late-night dip sessions.',
      sellerHandle: 'atelier_tech',
    ),
  ];
});

/// Resolved [Drop] for detail routes (comments, likes).
final dropByIdProvider = Provider.family<Drop?, String>((ref, id) {
  final drops = ref.watch(dropsProvider);
  for (final d in drops) {
    if (d.id == id) return d;
  }
  return null;
});

/// Logged-in user (self) — matches tab profile & feed “me”.
final userProfileProvider = Provider<UserProfile>((ref) {
  return UserProfile(
    id: 'me',
    username: '@ALEX_DROPS',
    displayName: 'Alex Obsidian',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80',
    bio:
        'Redefining the digital luxury landscape through minimalist curation and obsidian aesthetics.',
    followers: 12400,
    following: 850,
    dropsCount: 42,
    isFollowing: false,
  );
});

const _meHandle = 'alex_drops';

/// Mock public profiles keyed by feed username (lowercase, no @).
final publicProfilesMapProvider = Provider<Map<String, UserProfile>>((ref) {
  UserProfile p({
    required String handle,
    required String display,
    required String avatar,
    required String bio,
    int followers = 8000,
    int following = 400,
    int drops = 24,
  }) {
    return UserProfile(
      id: handle,
      username: '@${handle.toUpperCase()}',
      displayName: display,
      avatarUrl: avatar,
      bio: bio,
      followers: followers,
      following: following,
      dropsCount: drops,
      isFollowing: false,
    );
  }

  return {
    'elenav_studio': p(
      handle: 'elenav_studio',
      display: 'Elena V Studio',
      avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=300&q=80',
      bio: 'Tech setups, weekend drops, and clean lines. NYC.',
      followers: 28900,
      following: 890,
      drops: 38,
    ),
    'noir_room': p(
      handle: 'noir_room',
      display: 'Noir Room',
      avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=300&q=80',
      bio: 'Midnight curation. Berlin.',
      followers: 15200,
      following: 612,
      drops: 19,
    ),
    'squad_crafts': p(
      handle: 'squad_crafts',
      display: 'Squad Crafts',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80',
      bio: 'Footwear & daily carry. Portland-made energy.',
      followers: 22100,
      following: 540,
      drops: 31,
    ),
    'mono_gear': p(
      handle: 'mono_gear',
      display: 'Mono Gear',
      avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=300&q=80',
      bio: 'Desert tones, obsidian details. Tokyo.',
      followers: 9400,
      following: 320,
      drops: 17,
    ),
    'obsidian_audio': p(
      handle: 'obsidian_audio',
      display: 'Obsidian Audio',
      avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=300&q=80',
      bio: 'Sound you can feel. London.',
      followers: 41200,
      following: 1100,
      drops: 56,
    ),
    'atelier_tech': p(
      handle: 'atelier_tech',
      display: 'Atelier Tech',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80',
      bio: 'Precision gear for people who notice the details. Paris.',
      followers: 6700,
      following: 210,
      drops: 12,
    ),
    'neon_notions': p(
      handle: 'neon_notions',
      display: 'Neon Notions',
      avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=300&q=80',
      bio: 'Blue accents always win. Miami.',
      followers: 19800,
      following: 720,
      drops: 27,
    ),
    // Inbox threads ([inboxThreadsProvider]) — same handles & avatars as messages.
    'alexrivera': p(
      handle: 'alexrivera',
      display: 'Alex Rivera',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80',
      bio: 'Squad buys, Luna drops, and late-night fits. LA.',
      followers: 18400,
      following: 412,
      drops: 28,
    ),
    'sarahc': p(
      handle: 'sarahc',
      display: 'Sarah Chen',
      avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&w=300&q=80',
      bio: 'Tracking, logistics, zero drama. SF.',
      followers: 9200,
      following: 310,
      drops: 14,
    ),
    'marcus_vibe': p(
      handle: 'marcus_vibe',
      display: 'Marcus Thorne',
      avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=300&q=80',
      bio: 'Chrono enthusiast. If it ticks, I’m interested.',
      followers: 11200,
      following: 520,
      drops: 21,
    ),
    'lilavogue': p(
      handle: 'lilavogue',
      display: 'Lila Vogue',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=300&q=80',
      bio: 'Drop alerts & squad energy. NYC.',
      followers: 25600,
      following: 890,
      drops: 34,
    ),
    'jordan_steel': p(
      handle: 'jordan_steel',
      display: 'Jordan Steel',
      avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=300&q=80',
      bio: 'Pickup spots & meetups. Chicago.',
      followers: 7400,
      following: 198,
      drops: 11,
    ),
  };
});

/// Resolve profile for product seller row or `/profile/u/:handle`.
final profileByHandleProvider = Provider.family<UserProfile?, String>((ref, raw) {
  final h = raw.trim().toLowerCase().replaceAll('@', '');
  if (h.isEmpty || h == _meHandle) return ref.watch(userProfileProvider);
  return ref.watch(publicProfilesMapProvider)[h];
});
